/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.ijse.ms.view;

import java.text.SimpleDateFormat;
import java.util.Date;
import lk.ijse.ms.observer.Observer;

/**
 *
 * @author USER
 */
public class AdminDash extends javax.swing.JFrame implements Observer{

    /**
     * Creates new form AdminDash
     */
    public AdminDash() {
        initComponents();
        setDate();
        setTime();
        
        
        Dashbord dash = new Dashbord();
        pnlDashbrdLoading.removeAll();
        pnlDashbrdLoading.repaint();
        pnlDashbrdLoading.revalidate();
        dash.setSize(pnlDashbrdLoading.getSize());
        pnlDashbrdLoading.add(dash);
        dash.setVisible(true);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblMinimixe = new javax.swing.JLabel();
        lblDateAuto = new javax.swing.JLabel();
        lblTime = new javax.swing.JLabel();
        pnlLogo = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        pnlDashbrdLoading = new javax.swing.JPanel();
        pnlTopic = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lblSetting = new javax.swing.JLabel();
        lblReport = new javax.swing.JLabel();
        lblViewCustomer = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblDashbord = new javax.swing.JLabel();
        lblReserve = new javax.swing.JLabel();
        lblManageMovie = new javax.swing.JLabel();
        lblMangeSeat = new javax.swing.JLabel();
        lblClose = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblMinimixe.setBackground(new java.awt.Color(255, 0, 51));
        lblMinimixe.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblMinimixe.setForeground(new java.awt.Color(255, 255, 255));
        lblMinimixe.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMinimixe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/ms/image/Programming-Minimize-Window-icon.png"))); // NOI18N
        lblMinimixe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMinimixeMouseClicked(evt);
            }
        });
        jPanel1.add(lblMinimixe, new org.netbeans.lib.awtextra.AbsoluteConstraints(1290, 10, 30, 30));

        lblDateAuto.setBackground(new java.awt.Color(255, 255, 102));
        lblDateAuto.setFont(new java.awt.Font("Times New Roman", 1, 28)); // NOI18N
        lblDateAuto.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(lblDateAuto, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 50, 150, 30));

        lblTime.setBackground(new java.awt.Color(255, 255, 102));
        lblTime.setFont(new java.awt.Font("Times New Roman", 1, 28)); // NOI18N
        lblTime.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(lblTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 50, 140, 30));

        pnlLogo.setBackground(new java.awt.Color(204, 204, 204));
        pnlLogo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        pnlLogo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setBackground(new java.awt.Color(204, 204, 204));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/ms/image/LogoMovie.jpg"))); // NOI18N
        jLabel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jLabel3.setOpaque(true);
        pnlLogo.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 13, 152, 160));

        jLabel6.setBackground(new java.awt.Color(102, 102, 102));
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/ms/image/LogoMovie.jpg"))); // NOI18N
        jLabel6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jLabel6.setOpaque(true);
        pnlLogo.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 150, 160));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/ms/image/fghj.gif"))); // NOI18N
        pnlLogo.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 250, 180));

        jPanel1.add(pnlLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 250, 180));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/ms/image/newTitle.jpg"))); // NOI18N
        jLabel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jLabel2.setOpaque(true);
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 40, 1090, 50));

        pnlDashbrdLoading.setBackground(new java.awt.Color(255, 255, 255));
        pnlDashbrdLoading.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        pnlDashbrdLoading.setLayout(null);
        jPanel1.add(pnlDashbrdLoading, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 90, 1090, 670));

        pnlTopic.setBackground(new java.awt.Color(204, 204, 204));
        pnlTopic.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        pnlTopic.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/ms/image/User-Interface-Logout-icon.png"))); // NOI18N
        pnlTopic.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 430, 60, 50));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/ms/image/SEO-icon.png"))); // NOI18N
        pnlTopic.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, 60, -1));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/ms/image/settings-icon.png"))); // NOI18N
        pnlTopic.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 60, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/ms/image/Actions-view-process-own-icon.png"))); // NOI18N
        pnlTopic.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 60, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/ms/image/Sphere-Seat-icon(48).png"))); // NOI18N
        pnlTopic.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 60, 60));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/ms/image/File-Movies-icon.png"))); // NOI18N
        pnlTopic.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 128, 60, 60));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/ms/image/tickets-icon.png"))); // NOI18N
        pnlTopic.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 72, 60, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/ms/image/Downloads-2-icon.png"))); // NOI18N
        pnlTopic.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 12, 60, -1));

        lblSetting.setBackground(new java.awt.Color(204, 0, 0));
        lblSetting.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        lblSetting.setForeground(new java.awt.Color(255, 255, 255));
        lblSetting.setText("              Setting");
        lblSetting.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        lblSetting.setOpaque(true);
        lblSetting.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSettingMouseClicked(evt);
            }
        });
        pnlTopic.add(lblSetting, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 228, 55));

        lblReport.setBackground(new java.awt.Color(204, 0, 0));
        lblReport.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        lblReport.setForeground(new java.awt.Color(255, 255, 255));
        lblReport.setText("              Report");
        lblReport.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        lblReport.setOpaque(true);
        pnlTopic.add(lblReport, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, 228, 55));

        lblViewCustomer.setBackground(new java.awt.Color(204, 0, 0));
        lblViewCustomer.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        lblViewCustomer.setForeground(new java.awt.Color(255, 255, 255));
        lblViewCustomer.setText("              View Customer");
        lblViewCustomer.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        lblViewCustomer.setOpaque(true);
        lblViewCustomer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblViewCustomerMouseClicked(evt);
            }
        });
        pnlTopic.add(lblViewCustomer, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 228, 55));

        jLabel4.setBackground(new java.awt.Color(204, 0, 0));
        jLabel4.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("              Log Out");
        jLabel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel4.setOpaque(true);
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        pnlTopic.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 430, 228, 55));

        lblDashbord.setBackground(new java.awt.Color(204, 0, 0));
        lblDashbord.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        lblDashbord.setForeground(new java.awt.Color(255, 255, 255));
        lblDashbord.setText("              Dashbord");
        lblDashbord.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        lblDashbord.setOpaque(true);
        lblDashbord.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblDashbordMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblDashbordMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblDashbordMouseExited(evt);
            }
        });
        pnlTopic.add(lblDashbord, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 228, 55));

        lblReserve.setBackground(new java.awt.Color(204, 0, 0));
        lblReserve.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        lblReserve.setForeground(new java.awt.Color(255, 255, 255));
        lblReserve.setText("              Reserve");
        lblReserve.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        lblReserve.setOpaque(true);
        lblReserve.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblReserveMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblReserveMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblReserveMouseExited(evt);
            }
        });
        pnlTopic.add(lblReserve, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 228, 55));

        lblManageMovie.setBackground(new java.awt.Color(204, 0, 0));
        lblManageMovie.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        lblManageMovie.setForeground(new java.awt.Color(255, 255, 255));
        lblManageMovie.setText("              Manage Movie");
        lblManageMovie.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        lblManageMovie.setOpaque(true);
        lblManageMovie.setPreferredSize(new java.awt.Dimension(195, 33));
        lblManageMovie.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblManageMovieMouseClicked(evt);
            }
        });
        pnlTopic.add(lblManageMovie, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 226, 55));

        lblMangeSeat.setBackground(new java.awt.Color(204, 0, 0));
        lblMangeSeat.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        lblMangeSeat.setForeground(new java.awt.Color(255, 255, 255));
        lblMangeSeat.setText("              Manage Seat");
        lblMangeSeat.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        lblMangeSeat.setOpaque(true);
        lblMangeSeat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMangeSeatMouseClicked(evt);
            }
        });
        pnlTopic.add(lblMangeSeat, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 228, 55));

        jPanel1.add(pnlTopic, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 250, 500));

        lblClose.setBackground(new java.awt.Color(255, 0, 51));
        lblClose.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblClose.setForeground(new java.awt.Color(255, 255, 255));
        lblClose.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/ms/image/Actions-application-exit-icon.png"))); // NOI18N
        lblClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCloseMouseClicked(evt);
            }
        });
        jPanel1.add(lblClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(1320, 10, 30, 30));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setOpaque(true);
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 1340, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1366, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 768, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lblDashbordMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDashbordMouseEntered
        //        lblDashbord.setFont(new Font("Tahoma Bold Italic",4,24));
    }//GEN-LAST:event_lblDashbordMouseEntered

    private void lblDashbordMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDashbordMouseExited
        //        lblDashbord.setFont(new Font("Tahoma Bold Italic",4,18));
    }//GEN-LAST:event_lblDashbordMouseExited

    private void lblDashbordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDashbordMouseClicked
        Dashbord dash = new Dashbord();
        pnlDashbrdLoading.removeAll();
        pnlDashbrdLoading.repaint();
        pnlDashbrdLoading.revalidate();
        dash.setSize(pnlDashbrdLoading.getSize());
        pnlDashbrdLoading.add(dash);
        dash.setVisible(true);
    }//GEN-LAST:event_lblDashbordMouseClicked

    private void lblManageMovieMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblManageMovieMouseClicked
        ManageMovie manageMovie = new ManageMovie();
        pnlDashbrdLoading.removeAll();
        pnlDashbrdLoading.repaint();
        pnlDashbrdLoading.revalidate();
        manageMovie.setSize(pnlDashbrdLoading.getSize());
        pnlDashbrdLoading.add(manageMovie);
        manageMovie.setVisible(true);
    }//GEN-LAST:event_lblManageMovieMouseClicked

    private void lblMangeSeatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMangeSeatMouseClicked
        ManageSeat seatPrice = new ManageSeat();
        pnlDashbrdLoading.removeAll();
        pnlDashbrdLoading.repaint();
        pnlDashbrdLoading.revalidate();
        seatPrice.setSize(pnlDashbrdLoading.getSize());
        pnlDashbrdLoading.add(seatPrice);
        seatPrice.setVisible(true);
    }//GEN-LAST:event_lblMangeSeatMouseClicked

    private void lblViewCustomerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblViewCustomerMouseClicked
        ViewCustomer manageCustomer = new ViewCustomer();
        pnlDashbrdLoading.removeAll();
        pnlDashbrdLoading.repaint();
        pnlDashbrdLoading.revalidate();
        manageCustomer.setSize(pnlDashbrdLoading.getSize());
        pnlDashbrdLoading.add(manageCustomer);
        manageCustomer.setVisible(true);
    }//GEN-LAST:event_lblViewCustomerMouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        new Login().setVisible(true);
    }//GEN-LAST:event_jLabel4MouseClicked

    private void lblMinimixeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMinimixeMouseClicked
        this.setState(ICONIFIED);
    }//GEN-LAST:event_lblMinimixeMouseClicked

    private void lblCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCloseMouseClicked
        System.exit(0);
    }//GEN-LAST:event_lblCloseMouseClicked

    private void lblReserveMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblReserveMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_lblReserveMouseEntered

    private void lblReserveMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblReserveMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_lblReserveMouseExited

    private void lblReserveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblReserveMouseClicked
        BookingForm bf=new BookingForm();
        pnlDashbrdLoading.removeAll();
        pnlDashbrdLoading.repaint();
        pnlDashbrdLoading.revalidate();
        bf.setSize(pnlDashbrdLoading.getSize());
        pnlDashbrdLoading.add(bf);
        bf.setVisible(true);
    }//GEN-LAST:event_lblReserveMouseClicked

    private void lblSettingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSettingMouseClicked
        ManageUser manageUser=new ManageUser();
        pnlDashbrdLoading.removeAll();
        pnlDashbrdLoading.repaint();
        pnlDashbrdLoading.revalidate();
        manageUser.setSize(pnlDashbrdLoading.getSize());
        pnlDashbrdLoading.add(manageUser);
        manageUser.setVisible(true);
    }//GEN-LAST:event_lblSettingMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminDash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminDash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminDash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminDash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminDash().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblClose;
    private javax.swing.JLabel lblDashbord;
    private javax.swing.JLabel lblDateAuto;
    private javax.swing.JLabel lblManageMovie;
    private javax.swing.JLabel lblMangeSeat;
    private javax.swing.JLabel lblMinimixe;
    private javax.swing.JLabel lblReport;
    private javax.swing.JLabel lblReserve;
    private javax.swing.JLabel lblSetting;
    private javax.swing.JLabel lblTime;
    private javax.swing.JLabel lblViewCustomer;
    private javax.swing.JPanel pnlDashbrdLoading;
    private javax.swing.JPanel pnlLogo;
    private javax.swing.JPanel pnlTopic;
    // End of variables declaration//GEN-END:variables

    private void setDate() {
        java.util.Date d = new java.util.Date();
        SimpleDateFormat df = new SimpleDateFormat("YYYY-MM-dd");
        String formateDate = df.format(d);
        lblDateAuto.setText(formateDate);
    }

    private void setTime() {
        new Thread(new Runnable() {
            Date d = new Date();

            @Override
            public void run() {
                SimpleDateFormat sdf = new SimpleDateFormat("HH : mm : ss");
                String format = sdf.format(d);
                lblTime.setText(format);
                setTime();
            }
        }).start();
    }

    @Override
    public void updateObservers() throws Exception {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
