/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.ijse.ms.view;

import java.text.SimpleDateFormat;
import java.util.Date;
import lk.ijse.ms.observer.Observer;

/**
 *
 * @author USER
 */
public class ClientDash extends javax.swing.JFrame implements Observer{

    /**
     * Creates new form ClientDash
     */
    public ClientDash() {
        initComponents();
        setDate();
        setTime();
        
        Dashbord dash=new Dashbord();
        pnlDashbrdLoading.removeAll();
        pnlDashbrdLoading.repaint();
        pnlDashbrdLoading.revalidate();
        dash.setSize(pnlDashbrdLoading.getSize());
        pnlDashbrdLoading.add(dash);
        dash.setVisible(true);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblTime = new javax.swing.JLabel();
        lblDateAuto = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        pnlDashbrdLoading = new javax.swing.JPanel();
        pnlTopic = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblDashbord = new javax.swing.JLabel();
        lblReserv = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        pnlLogo = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lblClose = new javax.swing.JLabel();
        lblMinimixe = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTime.setBackground(new java.awt.Color(204, 204, 0));
        lblTime.setFont(new java.awt.Font("Times New Roman", 1, 28)); // NOI18N
        lblTime.setForeground(new java.awt.Color(255, 255, 255));
        lblTime.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(lblTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 50, 140, 30));

        lblDateAuto.setBackground(new java.awt.Color(204, 204, 0));
        lblDateAuto.setFont(new java.awt.Font("Times New Roman", 1, 28)); // NOI18N
        lblDateAuto.setForeground(new java.awt.Color(255, 255, 255));
        lblDateAuto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(lblDateAuto, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 50, 150, 30));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/ms/image/newTitle.jpg"))); // NOI18N
        jLabel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jLabel2.setOpaque(true);
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 40, 1090, 50));

        pnlDashbrdLoading.setBackground(new java.awt.Color(255, 255, 255));
        pnlDashbrdLoading.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        pnlDashbrdLoading.setLayout(null);
        jPanel1.add(pnlDashbrdLoading, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 90, 1090, 670));

        pnlTopic.setBackground(new java.awt.Color(204, 204, 204));
        pnlTopic.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        pnlTopic.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/ms/image/User-Interface-Logout-icon.png"))); // NOI18N
        pnlTopic.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, 50));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/ms/image/Downloads-2-icon.png"))); // NOI18N
        pnlTopic.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 12, 60, 60));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/ms/image/tickets-icon.png"))); // NOI18N
        pnlTopic.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 60, -1));
        pnlTopic.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 50, 50));

        lblDashbord.setBackground(new java.awt.Color(204, 0, 0));
        lblDashbord.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        lblDashbord.setForeground(new java.awt.Color(255, 255, 255));
        lblDashbord.setText("              Dashbord");
        lblDashbord.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        lblDashbord.setOpaque(true);
        lblDashbord.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblDashbordMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblDashbordMouseExited(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblDashbordMouseClicked(evt);
            }
        });
        pnlTopic.add(lblDashbord, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 228, 64));

        lblReserv.setBackground(new java.awt.Color(204, 0, 0));
        lblReserv.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        lblReserv.setForeground(new java.awt.Color(255, 255, 255));
        lblReserv.setText("              Reserve");
        lblReserv.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        lblReserv.setOpaque(true);
        lblReserv.setPreferredSize(new java.awt.Dimension(195, 33));
        lblReserv.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblReservMouseClicked(evt);
            }
        });
        pnlTopic.add(lblReserv, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 228, 64));

        jLabel4.setBackground(new java.awt.Color(204, 0, 0));
        jLabel4.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("              Log Out");
        jLabel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel4.setOpaque(true);
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        pnlTopic.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 228, 65));

        jLabel11.setText("jLabel11");
        pnlTopic.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, 50));

        jPanel1.add(pnlTopic, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 250, 230));

        pnlLogo.setBackground(new java.awt.Color(204, 204, 204));
        pnlLogo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        pnlLogo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setBackground(new java.awt.Color(204, 204, 204));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/ms/image/LogoMovie.jpg"))); // NOI18N
        jLabel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jLabel3.setOpaque(true);
        pnlLogo.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 13, 152, 160));

        jLabel6.setBackground(new java.awt.Color(102, 102, 102));
        jLabel6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jLabel6.setOpaque(true);
        pnlLogo.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 150, 160));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/ms/image/fghj.gif"))); // NOI18N
        pnlLogo.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 250, 180));

        jPanel1.add(pnlLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 250, 180));

        lblClose.setBackground(new java.awt.Color(255, 0, 51));
        lblClose.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblClose.setForeground(new java.awt.Color(255, 255, 255));
        lblClose.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/ms/image/Actions-application-exit-icon.png"))); // NOI18N
        lblClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCloseMouseClicked(evt);
            }
        });
        jPanel1.add(lblClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(1320, 10, 30, 30));

        lblMinimixe.setBackground(new java.awt.Color(255, 0, 51));
        lblMinimixe.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblMinimixe.setForeground(new java.awt.Color(255, 255, 255));
        lblMinimixe.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMinimixe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/ms/image/Programming-Minimize-Window-icon.png"))); // NOI18N
        lblMinimixe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMinimixeMouseClicked(evt);
            }
        });
        jPanel1.add(lblMinimixe, new org.netbeans.lib.awtextra.AbsoluteConstraints(1290, 10, 30, 30));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jLabel1.setOpaque(true);
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 1340, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1366, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 768, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblDashbordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDashbordMouseClicked
        Dashbord dash=new Dashbord();
        pnlDashbrdLoading.removeAll();
        pnlDashbrdLoading.repaint();
        pnlDashbrdLoading.revalidate();
        dash.setSize(pnlDashbrdLoading.getSize());
        pnlDashbrdLoading.add(dash);
        dash.setVisible(true);
    }//GEN-LAST:event_lblDashbordMouseClicked

    private void lblDashbordMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDashbordMouseEntered
        //        lblDashbord.setFont(new Font("Tahoma Bold Italic",4,24));
    }//GEN-LAST:event_lblDashbordMouseEntered

    private void lblDashbordMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDashbordMouseExited
        //        lblDashbord.setFont(new Font("Tahoma Bold Italic",4,18));
    }//GEN-LAST:event_lblDashbordMouseExited

    private void lblReservMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblReservMouseClicked
        BookingForm bookingForm=new BookingForm();
        pnlDashbrdLoading.removeAll();
        pnlDashbrdLoading.repaint();
        pnlDashbrdLoading.revalidate();
        bookingForm.setSize(pnlDashbrdLoading.getSize());
        pnlDashbrdLoading.add(bookingForm);
        bookingForm.setVisible(true);
    }//GEN-LAST:event_lblReservMouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        new Login().setVisible(true);
    }//GEN-LAST:event_jLabel4MouseClicked

    private void lblCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCloseMouseClicked
        System.exit(0);
    }//GEN-LAST:event_lblCloseMouseClicked

    private void lblMinimixeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMinimixeMouseClicked
        this.setState(ICONIFIED);
    }//GEN-LAST:event_lblMinimixeMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClientDash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClientDash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClientDash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClientDash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClientDash().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblClose;
    private javax.swing.JLabel lblDashbord;
    private javax.swing.JLabel lblDateAuto;
    private javax.swing.JLabel lblMinimixe;
    private javax.swing.JLabel lblReserv;
    private javax.swing.JLabel lblTime;
    private javax.swing.JPanel pnlDashbrdLoading;
    private javax.swing.JPanel pnlLogo;
    private javax.swing.JPanel pnlTopic;
    // End of variables declaration//GEN-END:variables

    private void setTime() {
        new Thread(new Runnable() {
            Date d = new Date();

            @Override
            public void run() {
                SimpleDateFormat sdf = new SimpleDateFormat("HH : mm : ss");
                String format = sdf.format(d);
                lblTime.setText(format);
                setTime();
            }
        }).start();
    }

    private void setDate() {
        java.util.Date d = new java.util.Date();
        SimpleDateFormat df = new SimpleDateFormat("YYYY-MM-dd");
        String formateDate = df.format(d);
        lblDateAuto.setText(formateDate);
    }

    @Override
    public void updateObservers() throws Exception {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
