/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.ijse.ms.view;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.Timer;

/**
 *
 * @author USER
 */
public class Dashbord extends javax.swing.JPanel {

    /**
     * Creates new form Dashbord
     */
    public Dashbord() {
        initComponents();
        
        slideShow();
        
        lblSlide.setLocation(-lblSlide.getWidth(),0);
        
        Timer timer=new Timer(100,new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                int x =lblSlide.getLocation().x;
                int y =lblSlide.getLocation().y;
                
                x +=25;
                lblSlide.setLocation(x,y);
                
                if(x > Dashbord.this.getWidth()){
                    lblSlide.setLocation(-lblSlide.getWidth(),0);
                }
            }
        });
        timer.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        pnlSlider = new javax.swing.JPanel();
        lblSlide = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        lblCustomerCount1 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel15 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblReserveName = new javax.swing.JLabel();
        lblReserCount = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel16 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblMovieCount = new javax.swing.JLabel();
        lblMovieName = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblCustomerName = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lblCustomerCount = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel13 = new javax.swing.JLabel();
        lblPayNmae = new javax.swing.JLabel();
        lblPayrCount = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel14 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlSlider.setBackground(new java.awt.Color(255, 255, 204));

        lblSlide.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/ms/image/slider1.jpg"))); // NOI18N

        javax.swing.GroupLayout pnlSliderLayout = new javax.swing.GroupLayout(pnlSlider);
        pnlSlider.setLayout(pnlSliderLayout);
        pnlSliderLayout.setHorizontalGroup(
            pnlSliderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSliderLayout.createSequentialGroup()
                .addComponent(lblSlide, javax.swing.GroupLayout.PREFERRED_SIZE, 748, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 302, Short.MAX_VALUE))
        );
        pnlSliderLayout.setVerticalGroup(
            pnlSliderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSliderLayout.createSequentialGroup()
                .addComponent(lblSlide, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 5, Short.MAX_VALUE))
        );

        jPanel1.add(pnlSlider, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 1050, 280));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Client >> Dashbord");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 0, 140, 20));

        jLabel17.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 410, 80, 100));

        lblCustomerCount1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lblCustomerCount1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCustomerCount1.setText("05");
        jPanel1.add(lblCustomerCount1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 460, 110, 30));

        jSeparator5.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 400, 10, 120));

        jLabel15.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 410, 80, 100));

        jLabel11.setBackground(new java.awt.Color(0, 0, 0));
        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("More Detail >>");
        jLabel11.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jLabel11.setOpaque(true);
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 520, 230, 20));

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jLabel3.setOpaque(true);
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1090, 20));

        lblReserveName.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lblReserveName.setText("Manage Reserve");
        jPanel1.add(lblReserveName, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 420, 110, 30));

        lblReserCount.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lblReserCount.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblReserCount.setText("00");
        jPanel1.add(lblReserCount, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 460, 100, 30));

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 400, 10, 120));

        jLabel16.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 410, 80, 100));

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("More Detail >>");
        jLabel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jLabel1.setOpaque(true);
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 520, 230, 20));

        lblMovieCount.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lblMovieCount.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMovieCount.setText("03");
        jPanel1.add(lblMovieCount, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 460, 110, 30));

        lblMovieName.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lblMovieName.setText("Manage Movie");
        jPanel1.add(lblMovieName, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 420, 110, 30));

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 400, 10, 120));

        jLabel8.setBackground(new java.awt.Color(0, 0, 0));
        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("More Detail >>");
        jLabel8.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jLabel8.setOpaque(true);
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 520, 230, 20));

        jLabel2.setBackground(new java.awt.Color(204, 51, 0));
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 0), 2));
        jLabel2.setOpaque(true);
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 400, 230, 140));

        lblCustomerName.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lblCustomerName.setText("Manage Seat");
        jPanel1.add(lblCustomerName, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 420, 120, 30));

        jLabel6.setBackground(new java.awt.Color(51, 204, 0));
        jLabel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 0), 2));
        jLabel6.setOpaque(true);
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 400, 230, 140));

        jLabel9.setBackground(new java.awt.Color(0, 0, 0));
        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("More Detail >>");
        jLabel9.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jLabel9.setOpaque(true);
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 520, 230, 20));

        lblCustomerCount.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lblCustomerCount.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCustomerCount.setText("00");
        jPanel1.add(lblCustomerCount, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 460, 110, 30));

        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 400, 10, 120));

        jLabel13.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 410, 80, 100));

        lblPayNmae.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lblPayNmae.setText("Manage Theret");
        jPanel1.add(lblPayNmae, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 420, 120, 30));

        lblPayrCount.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lblPayrCount.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPayrCount.setText("02");
        jPanel1.add(lblPayrCount, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 460, 110, 30));

        jSeparator4.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 400, 10, 120));

        jLabel14.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 410, 80, 100));

        jLabel10.setBackground(new java.awt.Color(0, 0, 0));
        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("More Detail >>");
        jLabel10.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jLabel10.setOpaque(true);
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 520, 230, 20));

        jLabel7.setBackground(new java.awt.Color(255, 102, 204));
        jLabel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 0), 2));
        jLabel7.setOpaque(true);
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 400, 230, 140));

        jLabel5.setBackground(new java.awt.Color(255, 204, 51));
        jLabel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 0), 2));
        jLabel5.setOpaque(true);
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, 230, 140));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 670, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked

    }//GEN-LAST:event_jLabel1MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JLabel lblCustomerCount;
    private javax.swing.JLabel lblCustomerCount1;
    private javax.swing.JLabel lblCustomerName;
    private javax.swing.JLabel lblMovieCount;
    private javax.swing.JLabel lblMovieName;
    private javax.swing.JLabel lblPayNmae;
    private javax.swing.JLabel lblPayrCount;
    private javax.swing.JLabel lblReserCount;
    private javax.swing.JLabel lblReserveName;
    private javax.swing.JLabel lblSlide;
    private javax.swing.JPanel pnlSlider;
    // End of variables declaration//GEN-END:variables

    private void slideShow() {
        new Thread(){
            int count;
            @Override
            public void run(){
                try {
                    while(true){
                       switch(count){
                           case 0:
                               
                               break;
                       } 
                    }
                } catch (Exception e) {
                }
            }
            
        }.start();
    }
}
