/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.ijse.ms.view;

import com.sun.org.apache.xml.internal.dtm.DTM;
import java.rmi.server.UnicastRemoteObject;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import lk.ijse.ms.controller.SeatController;
import lk.ijse.ms.controller.ThereatController;
import lk.ijse.ms.dto.SeatDTO;
import lk.ijse.ms.dto.ThereatDTO;
import lk.ijse.ms.observer.Observer;

/**
 *
 * @author USER
 */
public class ManageSeat extends javax.swing.JPanel implements Observer {

    ThereatDTO tddto;

    /**
     * Creates new form ManageSeat
     */
    public ManageSeat() {
        initComponents();
        loadComboThereat();
        loadTable();
        
       
        try {
            UnicastRemoteObject.exportObject(this, 0);
            SeatController.getSubject().registerObserver(this);
        } catch (Exception ex) {
            Logger.getLogger(Thereat.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        ck01 = new javax.swing.JCheckBox();
        ck02 = new javax.swing.JCheckBox();
        ck03 = new javax.swing.JCheckBox();
        ck04 = new javax.swing.JCheckBox();
        ck05 = new javax.swing.JCheckBox();
        ck06 = new javax.swing.JCheckBox();
        ck07 = new javax.swing.JCheckBox();
        ck10 = new javax.swing.JCheckBox();
        ck11 = new javax.swing.JCheckBox();
        ck12 = new javax.swing.JCheckBox();
        ck13 = new javax.swing.JCheckBox();
        ck14 = new javax.swing.JCheckBox();
        ck15 = new javax.swing.JCheckBox();
        ck16 = new javax.swing.JCheckBox();
        ck19 = new javax.swing.JCheckBox();
        ck20 = new javax.swing.JCheckBox();
        ck21 = new javax.swing.JCheckBox();
        ck22 = new javax.swing.JCheckBox();
        ck23 = new javax.swing.JCheckBox();
        ck24 = new javax.swing.JCheckBox();
        ck25 = new javax.swing.JCheckBox();
        ck28 = new javax.swing.JCheckBox();
        ck29 = new javax.swing.JCheckBox();
        ck31 = new javax.swing.JCheckBox();
        ck30 = new javax.swing.JCheckBox();
        ck32 = new javax.swing.JCheckBox();
        ck33 = new javax.swing.JCheckBox();
        ck34 = new javax.swing.JCheckBox();
        ck37 = new javax.swing.JCheckBox();
        ck38 = new javax.swing.JCheckBox();
        ck39 = new javax.swing.JCheckBox();
        ck40 = new javax.swing.JCheckBox();
        ck41 = new javax.swing.JCheckBox();
        ck42 = new javax.swing.JCheckBox();
        ck43 = new javax.swing.JCheckBox();
        ck08 = new javax.swing.JCheckBox();
        ck17 = new javax.swing.JCheckBox();
        ck26 = new javax.swing.JCheckBox();
        ck35 = new javax.swing.JCheckBox();
        ck44 = new javax.swing.JCheckBox();
        ck09 = new javax.swing.JCheckBox();
        ck18 = new javax.swing.JCheckBox();
        ck27 = new javax.swing.JCheckBox();
        ck36 = new javax.swing.JCheckBox();
        ck45 = new javax.swing.JCheckBox();
        jPanel4 = new javax.swing.JPanel();
        txtFullPrice = new javax.swing.JTextField();
        lblSeatPrice = new javax.swing.JLabel();
        txtSeatType = new javax.swing.JTextField();
        lblSeatType = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel17 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        lblTheredName = new javax.swing.JLabel();
        lblNew = new javax.swing.JLabel();
        cmbTheredName = new javax.swing.JComboBox<>();
        jPanel5 = new javax.swing.JPanel();
        lblSeatNo = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        btnDelete = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSeat = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        btnUpdate = new javax.swing.JButton();
        jTextField4 = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel11 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel2.setPreferredSize(new java.awt.Dimension(1080, 660));
        jPanel2.setLayout(null);

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Admin >>Set Price");
        jPanel2.add(jLabel19);
        jLabel19.setBounds(940, 0, 130, 20);

        jLabel18.setBackground(new java.awt.Color(102, 102, 102));
        jLabel18.setOpaque(true);
        jPanel2.add(jLabel18);
        jLabel18.setBounds(0, 0, 1090, 20);

        jPanel3.setBackground(new java.awt.Color(255, 255, 204));
        jPanel3.setLayout(null);

        jPanel6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        ck01.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ck01.setText("01");
        ck01.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        ck02.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ck02.setText("02");
        ck02.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        ck03.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ck03.setText("03");
        ck03.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        ck04.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ck04.setText("04");
        ck04.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        ck05.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ck05.setText("05");
        ck05.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        ck06.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ck06.setText("06");
        ck06.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        ck07.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ck07.setText("07");
        ck07.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        ck10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ck10.setText("10");
        ck10.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        ck11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ck11.setText("11");
        ck11.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        ck12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ck12.setText("12");
        ck12.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        ck13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ck13.setText("13");
        ck13.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        ck14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ck14.setText("14");
        ck14.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        ck15.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ck15.setText("15");
        ck15.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        ck16.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ck16.setText("16");
        ck16.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        ck19.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ck19.setText("19");
        ck19.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        ck20.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ck20.setText("20");
        ck20.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        ck21.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ck21.setText("21");
        ck21.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        ck22.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ck22.setText("22");
        ck22.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        ck23.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ck23.setText("23");
        ck23.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        ck24.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ck24.setText("24");
        ck24.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        ck25.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ck25.setText("25");
        ck25.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        ck28.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ck28.setText("28");
        ck28.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        ck29.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ck29.setText("29");
        ck29.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        ck31.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ck31.setText("31");
        ck31.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        ck30.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ck30.setText("30");
        ck30.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        ck32.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ck32.setText("32");
        ck32.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        ck33.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ck33.setText("33");
        ck33.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        ck34.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ck34.setText("34");
        ck34.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        ck37.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ck37.setText("37");
        ck37.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        ck38.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ck38.setText("38");
        ck38.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        ck39.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ck39.setText("39");
        ck39.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        ck40.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ck40.setText("40");
        ck40.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        ck41.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ck41.setText("41");
        ck41.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        ck42.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ck42.setText("42");
        ck42.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        ck43.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ck43.setText("43");
        ck43.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        ck08.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ck08.setText("08");
        ck08.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        ck17.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ck17.setText("17");
        ck17.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        ck26.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ck26.setText("26");
        ck26.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        ck35.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ck35.setText("35");
        ck35.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        ck44.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ck44.setText("44");
        ck44.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        ck09.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ck09.setText("09");
        ck09.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        ck18.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ck18.setText("18");
        ck18.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        ck27.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ck27.setText("27");
        ck27.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        ck36.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ck36.setText("36");
        ck36.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        ck45.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ck45.setText("45");
        ck45.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(ck19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ck20)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ck21)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ck22)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ck23)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ck24)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ck25)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ck26)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ck27))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(ck01)
                        .addGap(7, 7, 7)
                        .addComponent(ck02)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ck03)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ck04)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ck05)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ck06)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ck07)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ck08)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ck09))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(ck10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ck11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ck12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ck13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ck14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ck15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ck16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ck17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ck18))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(ck28)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ck29)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ck30)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ck31)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ck32)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ck33)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ck34)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ck35)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ck36))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(ck37)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ck38)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ck39)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ck40)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ck41)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ck42)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ck43)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ck44)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ck45)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ck01)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ck02)
                        .addComponent(ck03)
                        .addComponent(ck04)
                        .addComponent(ck05)
                        .addComponent(ck06)
                        .addComponent(ck07)
                        .addComponent(ck08)
                        .addComponent(ck09)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ck10)
                    .addComponent(ck11)
                    .addComponent(ck12)
                    .addComponent(ck13)
                    .addComponent(ck14)
                    .addComponent(ck15)
                    .addComponent(ck16)
                    .addComponent(ck17)
                    .addComponent(ck18))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ck19)
                    .addComponent(ck20)
                    .addComponent(ck21)
                    .addComponent(ck22)
                    .addComponent(ck23)
                    .addComponent(ck24)
                    .addComponent(ck25)
                    .addComponent(ck26)
                    .addComponent(ck27))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ck28)
                    .addComponent(ck29)
                    .addComponent(ck30)
                    .addComponent(ck31)
                    .addComponent(ck32)
                    .addComponent(ck33)
                    .addComponent(ck34)
                    .addComponent(ck35)
                    .addComponent(ck36))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ck37)
                    .addComponent(ck38)
                    .addComponent(ck39)
                    .addComponent(ck40)
                    .addComponent(ck41)
                    .addComponent(ck42)
                    .addComponent(ck43)
                    .addComponent(ck44)
                    .addComponent(ck45)))
        );

        jPanel3.add(jPanel6);
        jPanel6.setBounds(370, 490, 390, 120);

        jPanel4.setBackground(new java.awt.Color(204, 204, 204));
        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtFullPrice.setBackground(new java.awt.Color(102, 102, 102));
        txtFullPrice.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtFullPrice.setForeground(new java.awt.Color(255, 255, 255));
        txtFullPrice.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtFullPrice.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel4.add(txtFullPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, 290, 30));

        lblSeatPrice.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lblSeatPrice.setText("Seat price       :");
        jPanel4.add(lblSeatPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, 120, 50));

        txtSeatType.setBackground(new java.awt.Color(102, 102, 102));
        txtSeatType.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtSeatType.setForeground(new java.awt.Color(255, 255, 255));
        txtSeatType.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtSeatType.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel4.add(txtSeatType, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 290, 30));

        lblSeatType.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lblSeatType.setText("Seat Type     :");
        jPanel4.add(lblSeatType, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 120, 30));
        jPanel4.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 300, -1));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 204));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("Add Seat Detail");
        jPanel4.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 140, 30));

        jLabel3.setBackground(new java.awt.Color(204, 0, 0));
        jLabel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jLabel3.setOpaque(true);
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 310, 30));

        jSeparator4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel4.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 310, 10));

        lblTheredName.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lblTheredName.setText("Thered Name    :");
        jPanel4.add(lblTheredName, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 120, 40));

        lblNew.setBackground(new java.awt.Color(0, 102, 255));
        lblNew.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lblNew.setForeground(new java.awt.Color(255, 255, 255));
        lblNew.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNew.setText("New ");
        lblNew.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        lblNew.setOpaque(true);
        lblNew.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblNewMouseClicked(evt);
            }
        });
        jPanel4.add(lblNew, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 180, 80, 30));

        cmbTheredName.setBackground(new java.awt.Color(153, 153, 153));
        cmbTheredName.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        cmbTheredName.setForeground(new java.awt.Color(255, 255, 255));
        cmbTheredName.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        cmbTheredName.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbTheredNameItemStateChanged(evt);
            }
        });
        jPanel4.add(cmbTheredName, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 290, 30));

        jPanel5.setBackground(new java.awt.Color(204, 204, 204));
        jPanel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblSeatNo.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lblSeatNo.setText("Number Of Seat     :");
        jPanel5.add(lblSeatNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 130, 30));

        txtId.setBackground(new java.awt.Color(102, 102, 102));
        txtId.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtId.setForeground(new java.awt.Color(255, 255, 255));
        txtId.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtId.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel5.add(txtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 270, 30));

        jPanel4.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 290, 80));

        btnSave.setBackground(new java.awt.Color(0, 51, 204));
        btnSave.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSave.setForeground(new java.awt.Color(255, 255, 255));
        btnSave.setText("Save");
        btnSave.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        jPanel4.add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 460, 110, 40));

        jPanel3.add(jPanel4);
        jPanel4.setBounds(30, 20, 310, 580);

        jLabel4.setBackground(new java.awt.Color(204, 204, 204));
        jLabel4.setOpaque(true);
        jPanel3.add(jLabel4);
        jLabel4.setBounds(20, 10, 340, 610);

        jPanel7.setBackground(new java.awt.Color(204, 204, 204));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel7.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, 30, 40));

        btnDelete.setBackground(new java.awt.Color(255, 0, 51));
        btnDelete.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnDelete.setForeground(new java.awt.Color(255, 255, 255));
        btnDelete.setText("Delete");
        btnDelete.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel7.add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 400, 110, 40));

        tblSeat.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Seat Number", "Is Booking", "Seat Type", "Seat Price", "Thereat Name"
            }
        ));
        jScrollPane1.setViewportView(tblSeat);

        jPanel7.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 111, 640, 270));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel2.setText("Serch Manage Seat");
        jPanel7.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 67, 136, 33));

        btnUpdate.setBackground(new java.awt.Color(0, 51, 204));
        btnUpdate.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnUpdate.setForeground(new java.awt.Color(255, 255, 255));
        btnUpdate.setText("Update");
        btnUpdate.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel7.add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, 110, 40));

        jTextField4.setBackground(new java.awt.Color(102, 102, 102));
        jTextField4.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jTextField4.setForeground(new java.awt.Color(255, 255, 255));
        jTextField4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel7.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 70, 193, 33));

        jSeparator3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel7.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 680, 10));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 204));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("View Manage Seat");
        jPanel7.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 190, 30));

        jLabel8.setBackground(new java.awt.Color(204, 0, 0));
        jLabel8.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jLabel8.setOpaque(true);
        jPanel7.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 680, 30));

        jPanel3.add(jPanel7);
        jPanel7.setBounds(370, 10, 680, 460);

        jLabel9.setBackground(new java.awt.Color(204, 204, 204));
        jLabel9.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), null, null));
        jLabel9.setOpaque(true);
        jPanel3.add(jLabel9);
        jLabel9.setBounds(340, 480, 710, 140);

        jPanel2.add(jPanel3);
        jPanel3.setBounds(10, 30, 1070, 630);

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1090, 670));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void lblNewMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNewMouseClicked
        new Thereat().setVisible(true);
    }//GEN-LAST:event_lblNewMouseClicked

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        try {
            SeatDTO seatDTO=new SeatDTO(txtId.getText(), false, txtSeatType.getText(), Double.parseDouble(txtFullPrice.getText()), tddto);

            boolean isAdded = SeatController.addSeat(seatDTO);

            if (isAdded) {
                JOptionPane.showMessageDialog(this, "Added Successfull");
            } else {
                JOptionPane.showMessageDialog(this, "Added Faild");
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void cmbTheredNameItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbTheredNameItemStateChanged
        try {
            List<ThereatDTO> dTOs = ThereatController.getAllThereat();
            for (ThereatDTO dTO : dTOs) {
                if (dTO.getThereatName().equals(cmbTheredName.getSelectedItem().toString())) {
                    tddto = dTO;
                }
            }
        } catch (Exception ex) {
            Logger.getLogger(ManageSeat.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_cmbTheredNameItemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JCheckBox ck01;
    private javax.swing.JCheckBox ck02;
    private javax.swing.JCheckBox ck03;
    private javax.swing.JCheckBox ck04;
    private javax.swing.JCheckBox ck05;
    private javax.swing.JCheckBox ck06;
    private javax.swing.JCheckBox ck07;
    private javax.swing.JCheckBox ck08;
    private javax.swing.JCheckBox ck09;
    private javax.swing.JCheckBox ck10;
    private javax.swing.JCheckBox ck11;
    private javax.swing.JCheckBox ck12;
    private javax.swing.JCheckBox ck13;
    private javax.swing.JCheckBox ck14;
    private javax.swing.JCheckBox ck15;
    private javax.swing.JCheckBox ck16;
    private javax.swing.JCheckBox ck17;
    private javax.swing.JCheckBox ck18;
    private javax.swing.JCheckBox ck19;
    private javax.swing.JCheckBox ck20;
    private javax.swing.JCheckBox ck21;
    private javax.swing.JCheckBox ck22;
    private javax.swing.JCheckBox ck23;
    private javax.swing.JCheckBox ck24;
    private javax.swing.JCheckBox ck25;
    private javax.swing.JCheckBox ck26;
    private javax.swing.JCheckBox ck27;
    private javax.swing.JCheckBox ck28;
    private javax.swing.JCheckBox ck29;
    private javax.swing.JCheckBox ck30;
    private javax.swing.JCheckBox ck31;
    private javax.swing.JCheckBox ck32;
    private javax.swing.JCheckBox ck33;
    private javax.swing.JCheckBox ck34;
    private javax.swing.JCheckBox ck35;
    private javax.swing.JCheckBox ck36;
    private javax.swing.JCheckBox ck37;
    private javax.swing.JCheckBox ck38;
    private javax.swing.JCheckBox ck39;
    private javax.swing.JCheckBox ck40;
    private javax.swing.JCheckBox ck41;
    private javax.swing.JCheckBox ck42;
    private javax.swing.JCheckBox ck43;
    private javax.swing.JCheckBox ck44;
    private javax.swing.JCheckBox ck45;
    private javax.swing.JComboBox<String> cmbTheredName;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JLabel lblNew;
    private javax.swing.JLabel lblSeatNo;
    private javax.swing.JLabel lblSeatPrice;
    private javax.swing.JLabel lblSeatType;
    private javax.swing.JLabel lblTheredName;
    private javax.swing.JTable tblSeat;
    private javax.swing.JTextField txtFullPrice;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtSeatType;
    // End of variables declaration//GEN-END:variables

    @Override
    public void updateObservers() throws Exception {
        loadComboThereat();
    }

    private void loadComboThereat() {
        try {
            List<ThereatDTO> allThereat = ThereatController.getAllThereat();
            cmbTheredName.removeAllItems();
            if (allThereat != null) {
                for (ThereatDTO thereat : allThereat) {
                    cmbTheredName.addItem(thereat.getThereatName());
                }
            }

        } catch (Exception ex) {
            Logger.getLogger(ManageSeat.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void loadTable() {
        DefaultTableModel dtm = (DefaultTableModel) tblSeat.getModel();
        dtm.setRowCount(0);

        try {
            List<SeatDTO> seatDTOs = SeatController.getAllSeat();

            if (seatDTOs == null) {
                return;
            }

            for (SeatDTO seatDTO : seatDTOs) {
                Object[] rowData = {
                    seatDTO.getSeatNo(),
                    seatDTO.isIsbooked(),
                    seatDTO.getSeattype(),
                    seatDTO.getSeatPrice(),
                    seatDTO.getTheatrDTO().getThereatName()
                    
                };
                dtm.addRow(rowData);
            }

            
        } catch (Exception ex) {
            Logger.getLogger(ManageSeat.class.getName()).log(Level.SEVERE, null, ex);
        }
    }


}
